SELECT EVALUATION.URL
FROM WEBPAGES
INNER JOIN EVALUATION ON WEBPAGES.URL = EVALUATION.URL
WHERE EMAIL NOT IN (SELECT EMAIL
                    FROM EVALUATION WHERE EMAIL != 'x@a.ca');

SELECT EMAIL FROM EVALUATION WHERE EMAIL NOT IN (SELECT EMAIL from EVALUATION WHERE EMAIL != 'x@a.ca') GROUP BY EMAIL;-- emails of every evaluator except x@a.ca

SELECT EMAIL, URL, count(EMAIL) FROM EVALUATION GROUP BY EMAIL, URL;

-- QUESTION 9
SELECT URL FROM EVALUATION WHERE URL NOT IN (SELECT URL FROM EVALUATION WHERE EMAIL != 'x@a.ca');

-- Selects all evaluations that were only reviewed by 1 person
SELECT URL FROM EVALUATION WHERE EMAIL NOT IN (SELECT EMAIL FROM EVALUATION GROUP BY EMAIL HAVING count(EMAIL) > 1)

SELECT * FROM EVALUATION WHERE URL NOT IN (SELECT URL FROM EVALUATION WHERE EMAIL IN (SELECT EMAIL FROM EVALUATION GROUP BY URL, EMAIL HAVING count(EMAIL) = 1));

SELECT EMAIL, URL, count(EMAIL)
FROM EVALUATION
WHERE URL in (SELECT url from EVALUATION GROUP BY URL)
GROUP BY EMAIL, URL
;


select distinct url, count(*) from EVALUATION group by url;

select t1.url, t1.email from EVALUATION t1, (select distinct url, count(*) cnt from EVALUATION group by url) t2
where t1.url = t2.URL
and t2.cnt = 1;