CREATE TABLE BILLINGADDRESS
(
    STREETADDRESS VARCHAR(50) NOT NULL,
    CITY VARCHAR(20) NOT NULL,
    "Postal/Zip" VARCHAR(15) NOT NULL,
    COUNTRY VARCHAR(15) NOT NULL,
    BA_ID INT PRIMARY KEY NOT NULL
);
CREATE TABLE CARTDETAILS
(
    CARTID INT NOT NULL,
    COLOR VARCHAR(15) NOT NULL,
    SIZE VARCHAR(10) NOT NULL,
    MODELNAME VARCHAR(30) NOT NULL,
    QUANTITY INT DEFAULT 1 NOT NULL,
    CONSTRAINT CARTDETAILS_CARTID_COLOR_SIZE_MODELNAME_PK PRIMARY KEY (CARTID, COLOR, SIZE, MODELNAME)
);
CREATE TABLE CLOTHINGCATEGORY
(
    CATID INT PRIMARY KEY NOT NULL,
    CATNAME VARCHAR(50) NOT NULL,
    CATTYPE VARCHAR(20) NOT NULL,
    CATEGORYDISCOUNT INT DEFAULT 0 NOT NULL
);
COMMENT ON COLUMN CLOTHINGCATEGORY.CATEGORYDISCOUNT IS 'Displayed as percentage';
CREATE TABLE CLOTHINGMODEL
(
    MODELNAME VARCHAR(30) PRIMARY KEY NOT NULL,
    SEX VARCHAR(1) NOT NULL,
    AGERANGE VARCHAR(10),
    MODELDISCOUNT INT DEFAULT 0,
    PRICE FLOAT(53) NOT NULL,
    CATID INT NOT NULL
);
COMMENT ON COLUMN CLOTHINGMODEL.MODELDISCOUNT IS 'Percentage Values';
CREATE TABLE CLOTHINGUNIT
(
    COLOR VARCHAR(15) NOT NULL,
    RESTOCKDATE DATE,
    MODELNAME VARCHAR(30) NOT NULL,
    SIZE VARCHAR(10) NOT NULL,
    CONSTRAINT CLOTHINGUNIT_COLOR_SIZE_PK PRIMARY KEY (COLOR, MODELNAME, SIZE)
);
CREATE TABLE CUSTOMER
(
    EMAIL VARCHAR(100) PRIMARY KEY NOT NULL,
    LASTNAME VARCHAR(30),
    FIRSTNAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL
);
CREATE TABLE EMPLOYEE
(
    EID INT PRIMARY KEY NOT NULL,
    ENAME VARCHAR(20) NOT NULL,
    EMPLOYMENTDATE DATE NOT NULL,
    SALARY FLOAT(53)
);
CREATE TABLE ORDER
(
    ORDERID INT PRIMARY KEY NOT NULL,
    ORDERTYPE VARCHAR(10) NOT NULL,
    PAYMENTMETHOD VARCHAR(20) NOT NULL,
    ORDERDATE DATE DEFAULT CURRENT DATE NOT NULL,
    FINALAMOUNT FLOAT(53) NOT NULL,
    CUSTOMEREMAIL VARCHAR(100) NOT NULL,
    HANDLEDATE DATE,
    HANDLER INT,
    SHIPPINGID INT,
    BILLINGID INT,
    CARTID INT,
    TRACKINGNUMBER VARCHAR(13)
);
COMMENT ON COLUMN ORDER.ORDERTYPE IS 'PURCHASE or REFUND';
COMMENT ON COLUMN ORDER.PAYMENTMETHOD IS 'VISA/MASTERCARD/AMERICAN EXPRESS/PAYPAL/INTERAC';
COMMENT ON COLUMN ORDER.SHIPPINGID IS 'Shipping Address ID';
COMMENT ON COLUMN ORDER.BILLINGID IS 'Billing Address ID';
COMMENT ON COLUMN ORDER.CARTID IS 'Shopping Cart ID';
CREATE TABLE SHIPPINGADDRESS
(
    STREETADDRESS VARCHAR(50) NOT NULL,
    CITY VARCHAR(20) NOT NULL,
    "Postal/Zip" VARCHAR(15) NOT NULL,
    COUNTRY VARCHAR(15) NOT NULL,
    SA_ID INT PRIMARY KEY NOT NULL
);
CREATE TABLE SHIPPINGINFO
(
    TRACKINGNUMBER VARCHAR(13) PRIMARY KEY NOT NULL,
    SHIPPINGDATE DATE NOT NULL,
    SHIPPINGMETHOD VARCHAR(50) NOT NULL,
    ORDERID INT
);
COMMENT ON COLUMN SHIPPINGINFO.SHIPPINGMETHOD IS 'Regular/Expedited/Express';
CREATE TABLE SHOPPINGCART
(
    CARTID INT PRIMARY KEY NOT NULL,
    CUSTOMEREMAIL VARCHAR(40),
    ORDERID INT,
    DATECREATED DATE NOT NULL
);
CREATE TABLE UNITSTOCKING
(
    MODELNAME VARCHAR(30) NOT NULL,
    QUANTITYAVAILABLE INT NOT NULL,
    LOCATION VARCHAR(20) NOT NULL,
    COLOR VARCHAR(15) NOT NULL,
    SIZE VARCHAR(10) NOT NULL,
    CONSTRAINT UNITSTOCKING_COLOR_SIZE_PK PRIMARY KEY (COLOR, MODELNAME, SIZE, LOCATION)
);
COMMENT ON COLUMN UNITSTOCKING.QUANTITYAVAILABLE IS 'Current Stock';
CREATE TABLE WAREHOUSE
(
    LOCATION VARCHAR(20) PRIMARY KEY NOT NULL,
    MAXSTOCKCAPACITY INT NOT NULL
);
COMMENT ON COLUMN WAREHOUSE.MAXSTOCKCAPACITY IS 'In terms of units';
CREATE TABLE FOREIGNBILLS
(
    MODELNAME VARCHAR(30) NOT NULL,
    CATEGORYNAME VARCHAR(50) NOT NULL,
    SIZE VARCHAR(10) NOT NULL,
    COLOR VARCHAR(15) NOT NULL,
    USCITY VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(50) NOT NULL
);
CREATE TABLE YELLOWBUYERS
(
    FIRSTNAME VARCHAR(30) NOT NULL,
    LASTNAME VARCHAR(30),
    MODELNAME VARCHAR(30) NOT NULL,
    DATEOFCARTCREATION DATE NOT NULL
);
ALTER TABLE CARTDETAILS ADD FOREIGN KEY (CARTID) REFERENCES SHOPPINGCART (CARTID);
ALTER TABLE CARTDETAILS ADD FOREIGN KEY (SIZE) REFERENCES CLOTHINGUNIT (SIZE);
ALTER TABLE CLOTHINGMODEL ADD FOREIGN KEY (CATID) REFERENCES CLOTHINGCATEGORY (CATID);
ALTER TABLE CLOTHINGUNIT ADD FOREIGN KEY (MODELNAME) REFERENCES CLOTHINGMODEL (MODELNAME);
ALTER TABLE ORDER ADD FOREIGN KEY (CUSTOMEREMAIL) REFERENCES CUSTOMER (EMAIL);
ALTER TABLE ORDER ADD FOREIGN KEY (SHIPPINGID) REFERENCES SHIPPINGADDRESS (SA_ID);
ALTER TABLE ORDER ADD FOREIGN KEY (BILLINGID) REFERENCES BILLINGADDRESS (BA_ID);
ALTER TABLE ORDER ADD FOREIGN KEY (CARTID) REFERENCES SHOPPINGCART (CARTID);
ALTER TABLE SHIPPINGINFO ADD FOREIGN KEY (ORDERID) REFERENCES ORDER (ORDERID);
ALTER TABLE SHOPPINGCART ADD FOREIGN KEY (CUSTOMEREMAIL) REFERENCES CUSTOMER (EMAIL);
ALTER TABLE SHOPPINGCART ADD FOREIGN KEY (ORDERID) REFERENCES ORDER (ORDERID);
ALTER TABLE UNITSTOCKING ADD FOREIGN KEY (LOCATION) REFERENCES WAREHOUSE (LOCATION)CREATE FUNCTION EMPLOYMENTDATEEXTRACT(MYEID INTEGER);